package inflor.core.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransformMap.proto

public final class TransformMapProto {
  private TransformMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransformMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransformMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    java.util.List<TransformMapProto.TransformMap.TransformEntry> 
        getEntryList();
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    TransformMapProto.TransformMap.TransformEntry getEntry(int index);
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    int getEntryCount();
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    java.util.List<? extends TransformMapProto.TransformMap.TransformEntryOrBuilder> 
        getEntryOrBuilderList();
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    TransformMapProto.TransformMap.TransformEntryOrBuilder getEntryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TransformMap}
   */
  public static final class TransformMap extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TransformMap)
      TransformMapOrBuilder {
    // Use TransformMap.newBuilder() to construct.
    private TransformMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransformMap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransformMap defaultInstance;
    public static TransformMap getDefaultInstance() {
      return defaultInstance;
    }

    public TransformMap getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransformMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entry_ = new java.util.ArrayList<TransformMapProto.TransformMap.TransformEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entry_.add(input.readMessage(TransformMapProto.TransformMap.TransformEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransformMapProto.internal_static_TransformMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransformMapProto.internal_static_TransformMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransformMapProto.TransformMap.class, TransformMapProto.TransformMap.Builder.class);
    }

    public static com.google.protobuf.Parser<TransformMap> PARSER =
        new com.google.protobuf.AbstractParser<TransformMap>() {
      public TransformMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransformMap(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransformMap> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code TransformMap.TransformType}
     */
    public enum TransformType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGICLE = 0;</code>
       */
      LOGICLE(0, 0),
      /**
       * <code>LOG = 1;</code>
       */
      LOG(1, 1),
      /**
       * <code>LINEAR = 2;</code>
       */
      LINEAR(2, 2),
      /**
       * <code>BOUNDARY = 3;</code>
       */
      BOUNDARY(3, 3),
      ;

      /**
       * <code>LOGICLE = 0;</code>
       */
      public static final int LOGICLE_VALUE = 0;
      /**
       * <code>LOG = 1;</code>
       */
      public static final int LOG_VALUE = 1;
      /**
       * <code>LINEAR = 2;</code>
       */
      public static final int LINEAR_VALUE = 2;
      /**
       * <code>BOUNDARY = 3;</code>
       */
      public static final int BOUNDARY_VALUE = 3;


      public final int getNumber() { return value; }

      public static TransformType valueOf(int value) {
        switch (value) {
          case 0: return LOGICLE;
          case 1: return LOG;
          case 2: return LINEAR;
          case 3: return BOUNDARY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TransformType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<TransformType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TransformType>() {
              public TransformType findValueByNumber(int number) {
                return TransformType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return TransformMapProto.TransformMap.getDescriptor().getEnumTypes().get(0);
      }

      private static final TransformType[] VALUES = values();

      public static TransformType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private TransformType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TransformMap.TransformType)
    }

    public interface TransformOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TransformMap.Transform)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required string id = 1;</code>
       */
      java.lang.String getId();
      /**
       * <code>required string id = 1;</code>
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <code>required .TransformMap.TransformType type = 2;</code>
       */
      boolean hasType();
      /**
       * <code>required .TransformMap.TransformType type = 2;</code>
       */
      TransformMapProto.TransformMap.TransformType getType();

      /**
       * <code>optional double logicleT = 3;</code>
       */
      boolean hasLogicleT();
      /**
       * <code>optional double logicleT = 3;</code>
       */
      double getLogicleT();

      /**
       * <code>optional double logicleW = 4;</code>
       */
      boolean hasLogicleW();
      /**
       * <code>optional double logicleW = 4;</code>
       */
      double getLogicleW();

      /**
       * <code>optional double logicleM = 5;</code>
       */
      boolean hasLogicleM();
      /**
       * <code>optional double logicleM = 5;</code>
       */
      double getLogicleM();

      /**
       * <code>optional double logicleA = 6;</code>
       */
      boolean hasLogicleA();
      /**
       * <code>optional double logicleA = 6;</code>
       */
      double getLogicleA();

      /**
       * <code>optional double logMin = 7;</code>
       */
      boolean hasLogMin();
      /**
       * <code>optional double logMin = 7;</code>
       */
      double getLogMin();

      /**
       * <code>optional double logMax = 8;</code>
       */
      boolean hasLogMax();
      /**
       * <code>optional double logMax = 8;</code>
       */
      double getLogMax();

      /**
       * <code>optional double linMin = 9;</code>
       */
      boolean hasLinMin();
      /**
       * <code>optional double linMin = 9;</code>
       */
      double getLinMin();

      /**
       * <code>optional double linMax = 10;</code>
       */
      boolean hasLinMax();
      /**
       * <code>optional double linMax = 10;</code>
       */
      double getLinMax();

      /**
       * <code>optional double boundMin = 11;</code>
       */
      boolean hasBoundMin();
      /**
       * <code>optional double boundMin = 11;</code>
       */
      double getBoundMin();

      /**
       * <code>optional double boundMax = 12;</code>
       */
      boolean hasBoundMax();
      /**
       * <code>optional double boundMax = 12;</code>
       */
      double getBoundMax();
    }
    /**
     * Protobuf type {@code TransformMap.Transform}
     */
    public static final class Transform extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:TransformMap.Transform)
        TransformOrBuilder {
      // Use Transform.newBuilder() to construct.
      private Transform(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Transform(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Transform defaultInstance;
      public static Transform getDefaultInstance() {
        return defaultInstance;
      }

      public Transform getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Transform(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                id_ = bs;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                TransformMapProto.TransformMap.TransformType value = TransformMapProto.TransformMap.TransformType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                logicleT_ = input.readDouble();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                logicleW_ = input.readDouble();
                break;
              }
              case 41: {
                bitField0_ |= 0x00000010;
                logicleM_ = input.readDouble();
                break;
              }
              case 49: {
                bitField0_ |= 0x00000020;
                logicleA_ = input.readDouble();
                break;
              }
              case 57: {
                bitField0_ |= 0x00000040;
                logMin_ = input.readDouble();
                break;
              }
              case 65: {
                bitField0_ |= 0x00000080;
                logMax_ = input.readDouble();
                break;
              }
              case 73: {
                bitField0_ |= 0x00000100;
                linMin_ = input.readDouble();
                break;
              }
              case 81: {
                bitField0_ |= 0x00000200;
                linMax_ = input.readDouble();
                break;
              }
              case 89: {
                bitField0_ |= 0x00000400;
                boundMin_ = input.readDouble();
                break;
              }
              case 97: {
                bitField0_ |= 0x00000800;
                boundMax_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransformMapProto.internal_static_TransformMap_Transform_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransformMapProto.internal_static_TransformMap_Transform_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransformMapProto.TransformMap.Transform.class, TransformMapProto.TransformMap.Transform.Builder.class);
      }

      public static com.google.protobuf.Parser<Transform> PARSER =
          new com.google.protobuf.AbstractParser<Transform>() {
        public Transform parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Transform(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Transform> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private java.lang.Object id_;
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private TransformMapProto.TransformMap.TransformType type_;
      /**
       * <code>required .TransformMap.TransformType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .TransformMap.TransformType type = 2;</code>
       */
      public TransformMapProto.TransformMap.TransformType getType() {
        return type_;
      }

      public static final int LOGICLET_FIELD_NUMBER = 3;
      private double logicleT_;
      /**
       * <code>optional double logicleT = 3;</code>
       */
      public boolean hasLogicleT() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double logicleT = 3;</code>
       */
      public double getLogicleT() {
        return logicleT_;
      }

      public static final int LOGICLEW_FIELD_NUMBER = 4;
      private double logicleW_;
      /**
       * <code>optional double logicleW = 4;</code>
       */
      public boolean hasLogicleW() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double logicleW = 4;</code>
       */
      public double getLogicleW() {
        return logicleW_;
      }

      public static final int LOGICLEM_FIELD_NUMBER = 5;
      private double logicleM_;
      /**
       * <code>optional double logicleM = 5;</code>
       */
      public boolean hasLogicleM() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double logicleM = 5;</code>
       */
      public double getLogicleM() {
        return logicleM_;
      }

      public static final int LOGICLEA_FIELD_NUMBER = 6;
      private double logicleA_;
      /**
       * <code>optional double logicleA = 6;</code>
       */
      public boolean hasLogicleA() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double logicleA = 6;</code>
       */
      public double getLogicleA() {
        return logicleA_;
      }

      public static final int LOGMIN_FIELD_NUMBER = 7;
      private double logMin_;
      /**
       * <code>optional double logMin = 7;</code>
       */
      public boolean hasLogMin() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double logMin = 7;</code>
       */
      public double getLogMin() {
        return logMin_;
      }

      public static final int LOGMAX_FIELD_NUMBER = 8;
      private double logMax_;
      /**
       * <code>optional double logMax = 8;</code>
       */
      public boolean hasLogMax() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional double logMax = 8;</code>
       */
      public double getLogMax() {
        return logMax_;
      }

      public static final int LINMIN_FIELD_NUMBER = 9;
      private double linMin_;
      /**
       * <code>optional double linMin = 9;</code>
       */
      public boolean hasLinMin() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional double linMin = 9;</code>
       */
      public double getLinMin() {
        return linMin_;
      }

      public static final int LINMAX_FIELD_NUMBER = 10;
      private double linMax_;
      /**
       * <code>optional double linMax = 10;</code>
       */
      public boolean hasLinMax() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional double linMax = 10;</code>
       */
      public double getLinMax() {
        return linMax_;
      }

      public static final int BOUNDMIN_FIELD_NUMBER = 11;
      private double boundMin_;
      /**
       * <code>optional double boundMin = 11;</code>
       */
      public boolean hasBoundMin() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional double boundMin = 11;</code>
       */
      public double getBoundMin() {
        return boundMin_;
      }

      public static final int BOUNDMAX_FIELD_NUMBER = 12;
      private double boundMax_;
      /**
       * <code>optional double boundMax = 12;</code>
       */
      public boolean hasBoundMax() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional double boundMax = 12;</code>
       */
      public double getBoundMax() {
        return boundMax_;
      }

      private void initFields() {
        id_ = "";
        type_ = TransformMapProto.TransformMap.TransformType.LOGICLE;
        logicleT_ = 0D;
        logicleW_ = 0D;
        logicleM_ = 0D;
        logicleA_ = 0D;
        logMin_ = 0D;
        logMax_ = 0D;
        linMin_ = 0D;
        linMax_ = 0D;
        boundMin_ = 0D;
        boundMax_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, logicleT_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeDouble(4, logicleW_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeDouble(5, logicleM_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeDouble(6, logicleA_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeDouble(7, logMin_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeDouble(8, logMax_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          output.writeDouble(9, linMin_);
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          output.writeDouble(10, linMax_);
        }
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          output.writeDouble(11, boundMin_);
        }
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          output.writeDouble(12, boundMax_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, logicleT_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, logicleW_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(5, logicleM_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(6, logicleA_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(7, logMin_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(8, logMax_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(9, linMin_);
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(10, linMax_);
        }
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(11, boundMin_);
        }
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(12, boundMax_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static TransformMapProto.TransformMap.Transform parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TransformMapProto.TransformMap.Transform parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.Transform parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TransformMapProto.TransformMap.Transform parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.Transform parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static TransformMapProto.TransformMap.Transform parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.Transform parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static TransformMapProto.TransformMap.Transform parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.Transform parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static TransformMapProto.TransformMap.Transform parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(TransformMapProto.TransformMap.Transform prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TransformMap.Transform}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TransformMap.Transform)
          TransformMapProto.TransformMap.TransformOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return TransformMapProto.internal_static_TransformMap_Transform_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return TransformMapProto.internal_static_TransformMap_Transform_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  TransformMapProto.TransformMap.Transform.class, TransformMapProto.TransformMap.Transform.Builder.class);
        }

        // Construct using TransformMapProto.TransformMap.Transform.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = TransformMapProto.TransformMap.TransformType.LOGICLE;
          bitField0_ = (bitField0_ & ~0x00000002);
          logicleT_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          logicleW_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000008);
          logicleM_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000010);
          logicleA_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000020);
          logMin_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000040);
          logMax_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000080);
          linMin_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000100);
          linMax_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000200);
          boundMin_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000400);
          boundMax_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000800);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return TransformMapProto.internal_static_TransformMap_Transform_descriptor;
        }

        public TransformMapProto.TransformMap.Transform getDefaultInstanceForType() {
          return TransformMapProto.TransformMap.Transform.getDefaultInstance();
        }

        public TransformMapProto.TransformMap.Transform build() {
          TransformMapProto.TransformMap.Transform result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public TransformMapProto.TransformMap.Transform buildPartial() {
          TransformMapProto.TransformMap.Transform result = new TransformMapProto.TransformMap.Transform(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.logicleT_ = logicleT_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.logicleW_ = logicleW_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.logicleM_ = logicleM_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.logicleA_ = logicleA_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.logMin_ = logMin_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.logMax_ = logMax_;
          if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
            to_bitField0_ |= 0x00000100;
          }
          result.linMin_ = linMin_;
          if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
            to_bitField0_ |= 0x00000200;
          }
          result.linMax_ = linMax_;
          if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
            to_bitField0_ |= 0x00000400;
          }
          result.boundMin_ = boundMin_;
          if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
            to_bitField0_ |= 0x00000800;
          }
          result.boundMax_ = boundMax_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof TransformMapProto.TransformMap.Transform) {
            return mergeFrom((TransformMapProto.TransformMap.Transform)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(TransformMapProto.TransformMap.Transform other) {
          if (other == TransformMapProto.TransformMap.Transform.getDefaultInstance()) return this;
          if (other.hasId()) {
            bitField0_ |= 0x00000001;
            id_ = other.id_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasLogicleT()) {
            setLogicleT(other.getLogicleT());
          }
          if (other.hasLogicleW()) {
            setLogicleW(other.getLogicleW());
          }
          if (other.hasLogicleM()) {
            setLogicleM(other.getLogicleM());
          }
          if (other.hasLogicleA()) {
            setLogicleA(other.getLogicleA());
          }
          if (other.hasLogMin()) {
            setLogMin(other.getLogMin());
          }
          if (other.hasLogMax()) {
            setLogMax(other.getLogMax());
          }
          if (other.hasLinMin()) {
            setLinMin(other.getLinMin());
          }
          if (other.hasLinMax()) {
            setLinMax(other.getLinMax());
          }
          if (other.hasBoundMin()) {
            setBoundMin(other.getBoundMin());
          }
          if (other.hasBoundMax()) {
            setBoundMax(other.getBoundMax());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          TransformMapProto.TransformMap.Transform parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (TransformMapProto.TransformMap.Transform) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object id_ = "";
        /**
         * <code>required string id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string id = 1;</code>
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              id_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }

        private TransformMapProto.TransformMap.TransformType type_ = TransformMapProto.TransformMap.TransformType.LOGICLE;
        /**
         * <code>required .TransformMap.TransformType type = 2;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .TransformMap.TransformType type = 2;</code>
         */
        public TransformMapProto.TransformMap.TransformType getType() {
          return type_;
        }
        /**
         * <code>required .TransformMap.TransformType type = 2;</code>
         */
        public Builder setType(TransformMapProto.TransformMap.TransformType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .TransformMap.TransformType type = 2;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = TransformMapProto.TransformMap.TransformType.LOGICLE;
          onChanged();
          return this;
        }

        private double logicleT_ ;
        /**
         * <code>optional double logicleT = 3;</code>
         */
        public boolean hasLogicleT() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional double logicleT = 3;</code>
         */
        public double getLogicleT() {
          return logicleT_;
        }
        /**
         * <code>optional double logicleT = 3;</code>
         */
        public Builder setLogicleT(double value) {
          bitField0_ |= 0x00000004;
          logicleT_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double logicleT = 3;</code>
         */
        public Builder clearLogicleT() {
          bitField0_ = (bitField0_ & ~0x00000004);
          logicleT_ = 0D;
          onChanged();
          return this;
        }

        private double logicleW_ ;
        /**
         * <code>optional double logicleW = 4;</code>
         */
        public boolean hasLogicleW() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional double logicleW = 4;</code>
         */
        public double getLogicleW() {
          return logicleW_;
        }
        /**
         * <code>optional double logicleW = 4;</code>
         */
        public Builder setLogicleW(double value) {
          bitField0_ |= 0x00000008;
          logicleW_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double logicleW = 4;</code>
         */
        public Builder clearLogicleW() {
          bitField0_ = (bitField0_ & ~0x00000008);
          logicleW_ = 0D;
          onChanged();
          return this;
        }

        private double logicleM_ ;
        /**
         * <code>optional double logicleM = 5;</code>
         */
        public boolean hasLogicleM() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional double logicleM = 5;</code>
         */
        public double getLogicleM() {
          return logicleM_;
        }
        /**
         * <code>optional double logicleM = 5;</code>
         */
        public Builder setLogicleM(double value) {
          bitField0_ |= 0x00000010;
          logicleM_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double logicleM = 5;</code>
         */
        public Builder clearLogicleM() {
          bitField0_ = (bitField0_ & ~0x00000010);
          logicleM_ = 0D;
          onChanged();
          return this;
        }

        private double logicleA_ ;
        /**
         * <code>optional double logicleA = 6;</code>
         */
        public boolean hasLogicleA() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional double logicleA = 6;</code>
         */
        public double getLogicleA() {
          return logicleA_;
        }
        /**
         * <code>optional double logicleA = 6;</code>
         */
        public Builder setLogicleA(double value) {
          bitField0_ |= 0x00000020;
          logicleA_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double logicleA = 6;</code>
         */
        public Builder clearLogicleA() {
          bitField0_ = (bitField0_ & ~0x00000020);
          logicleA_ = 0D;
          onChanged();
          return this;
        }

        private double logMin_ ;
        /**
         * <code>optional double logMin = 7;</code>
         */
        public boolean hasLogMin() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional double logMin = 7;</code>
         */
        public double getLogMin() {
          return logMin_;
        }
        /**
         * <code>optional double logMin = 7;</code>
         */
        public Builder setLogMin(double value) {
          bitField0_ |= 0x00000040;
          logMin_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double logMin = 7;</code>
         */
        public Builder clearLogMin() {
          bitField0_ = (bitField0_ & ~0x00000040);
          logMin_ = 0D;
          onChanged();
          return this;
        }

        private double logMax_ ;
        /**
         * <code>optional double logMax = 8;</code>
         */
        public boolean hasLogMax() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional double logMax = 8;</code>
         */
        public double getLogMax() {
          return logMax_;
        }
        /**
         * <code>optional double logMax = 8;</code>
         */
        public Builder setLogMax(double value) {
          bitField0_ |= 0x00000080;
          logMax_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double logMax = 8;</code>
         */
        public Builder clearLogMax() {
          bitField0_ = (bitField0_ & ~0x00000080);
          logMax_ = 0D;
          onChanged();
          return this;
        }

        private double linMin_ ;
        /**
         * <code>optional double linMin = 9;</code>
         */
        public boolean hasLinMin() {
          return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>optional double linMin = 9;</code>
         */
        public double getLinMin() {
          return linMin_;
        }
        /**
         * <code>optional double linMin = 9;</code>
         */
        public Builder setLinMin(double value) {
          bitField0_ |= 0x00000100;
          linMin_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double linMin = 9;</code>
         */
        public Builder clearLinMin() {
          bitField0_ = (bitField0_ & ~0x00000100);
          linMin_ = 0D;
          onChanged();
          return this;
        }

        private double linMax_ ;
        /**
         * <code>optional double linMax = 10;</code>
         */
        public boolean hasLinMax() {
          return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        /**
         * <code>optional double linMax = 10;</code>
         */
        public double getLinMax() {
          return linMax_;
        }
        /**
         * <code>optional double linMax = 10;</code>
         */
        public Builder setLinMax(double value) {
          bitField0_ |= 0x00000200;
          linMax_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double linMax = 10;</code>
         */
        public Builder clearLinMax() {
          bitField0_ = (bitField0_ & ~0x00000200);
          linMax_ = 0D;
          onChanged();
          return this;
        }

        private double boundMin_ ;
        /**
         * <code>optional double boundMin = 11;</code>
         */
        public boolean hasBoundMin() {
          return ((bitField0_ & 0x00000400) == 0x00000400);
        }
        /**
         * <code>optional double boundMin = 11;</code>
         */
        public double getBoundMin() {
          return boundMin_;
        }
        /**
         * <code>optional double boundMin = 11;</code>
         */
        public Builder setBoundMin(double value) {
          bitField0_ |= 0x00000400;
          boundMin_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double boundMin = 11;</code>
         */
        public Builder clearBoundMin() {
          bitField0_ = (bitField0_ & ~0x00000400);
          boundMin_ = 0D;
          onChanged();
          return this;
        }

        private double boundMax_ ;
        /**
         * <code>optional double boundMax = 12;</code>
         */
        public boolean hasBoundMax() {
          return ((bitField0_ & 0x00000800) == 0x00000800);
        }
        /**
         * <code>optional double boundMax = 12;</code>
         */
        public double getBoundMax() {
          return boundMax_;
        }
        /**
         * <code>optional double boundMax = 12;</code>
         */
        public Builder setBoundMax(double value) {
          bitField0_ |= 0x00000800;
          boundMax_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double boundMax = 12;</code>
         */
        public Builder clearBoundMax() {
          bitField0_ = (bitField0_ & ~0x00000800);
          boundMax_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:TransformMap.Transform)
      }

      static {
        defaultInstance = new Transform(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:TransformMap.Transform)
    }

    public interface TransformEntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TransformMap.TransformEntry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>required .TransformMap.Transform entry = 2;</code>
       */
      boolean hasEntry();
      /**
       * <code>required .TransformMap.Transform entry = 2;</code>
       */
      TransformMapProto.TransformMap.Transform getEntry();
      /**
       * <code>required .TransformMap.Transform entry = 2;</code>
       */
      TransformMapProto.TransformMap.TransformOrBuilder getEntryOrBuilder();
    }
    /**
     * Protobuf type {@code TransformMap.TransformEntry}
     */
    public static final class TransformEntry extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:TransformMap.TransformEntry)
        TransformEntryOrBuilder {
      // Use TransformEntry.newBuilder() to construct.
      private TransformEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private TransformEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final TransformEntry defaultInstance;
      public static TransformEntry getDefaultInstance() {
        return defaultInstance;
      }

      public TransformEntry getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private TransformEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                key_ = bs;
                break;
              }
              case 18: {
                TransformMapProto.TransformMap.Transform.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = entry_.toBuilder();
                }
                entry_ = input.readMessage(TransformMapProto.TransformMap.Transform.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(entry_);
                  entry_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransformMapProto.internal_static_TransformMap_TransformEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransformMapProto.internal_static_TransformMap_TransformEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransformMapProto.TransformMap.TransformEntry.class, TransformMapProto.TransformMap.TransformEntry.Builder.class);
      }

      public static com.google.protobuf.Parser<TransformEntry> PARSER =
          new com.google.protobuf.AbstractParser<TransformEntry>() {
        public TransformEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransformEntry(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<TransformEntry> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ENTRY_FIELD_NUMBER = 2;
      private TransformMapProto.TransformMap.Transform entry_;
      /**
       * <code>required .TransformMap.Transform entry = 2;</code>
       */
      public boolean hasEntry() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .TransformMap.Transform entry = 2;</code>
       */
      public TransformMapProto.TransformMap.Transform getEntry() {
        return entry_;
      }
      /**
       * <code>required .TransformMap.Transform entry = 2;</code>
       */
      public TransformMapProto.TransformMap.TransformOrBuilder getEntryOrBuilder() {
        return entry_;
      }

      private void initFields() {
        key_ = "";
        entry_ = TransformMapProto.TransformMap.Transform.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEntry()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getEntry().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, entry_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, entry_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static TransformMapProto.TransformMap.TransformEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static TransformMapProto.TransformMap.TransformEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(TransformMapProto.TransformMap.TransformEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TransformMap.TransformEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TransformMap.TransformEntry)
          TransformMapProto.TransformMap.TransformEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return TransformMapProto.internal_static_TransformMap_TransformEntry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return TransformMapProto.internal_static_TransformMap_TransformEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  TransformMapProto.TransformMap.TransformEntry.class, TransformMapProto.TransformMap.TransformEntry.Builder.class);
        }

        // Construct using TransformMapProto.TransformMap.TransformEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getEntryFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (entryBuilder_ == null) {
            entry_ = TransformMapProto.TransformMap.Transform.getDefaultInstance();
          } else {
            entryBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return TransformMapProto.internal_static_TransformMap_TransformEntry_descriptor;
        }

        public TransformMapProto.TransformMap.TransformEntry getDefaultInstanceForType() {
          return TransformMapProto.TransformMap.TransformEntry.getDefaultInstance();
        }

        public TransformMapProto.TransformMap.TransformEntry build() {
          TransformMapProto.TransformMap.TransformEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public TransformMapProto.TransformMap.TransformEntry buildPartial() {
          TransformMapProto.TransformMap.TransformEntry result = new TransformMapProto.TransformMap.TransformEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (entryBuilder_ == null) {
            result.entry_ = entry_;
          } else {
            result.entry_ = entryBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof TransformMapProto.TransformMap.TransformEntry) {
            return mergeFrom((TransformMapProto.TransformMap.TransformEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(TransformMapProto.TransformMap.TransformEntry other) {
          if (other == TransformMapProto.TransformMap.TransformEntry.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasEntry()) {
            mergeEntry(other.getEntry());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasEntry()) {
            
            return false;
          }
          if (!getEntry().isInitialized()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          TransformMapProto.TransformMap.TransformEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (TransformMapProto.TransformMap.TransformEntry) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        private TransformMapProto.TransformMap.Transform entry_ = TransformMapProto.TransformMap.Transform.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            TransformMapProto.TransformMap.Transform, TransformMapProto.TransformMap.Transform.Builder, TransformMapProto.TransformMap.TransformOrBuilder> entryBuilder_;
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public boolean hasEntry() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public TransformMapProto.TransformMap.Transform getEntry() {
          if (entryBuilder_ == null) {
            return entry_;
          } else {
            return entryBuilder_.getMessage();
          }
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public Builder setEntry(TransformMapProto.TransformMap.Transform value) {
          if (entryBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            entry_ = value;
            onChanged();
          } else {
            entryBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public Builder setEntry(
            TransformMapProto.TransformMap.Transform.Builder builderForValue) {
          if (entryBuilder_ == null) {
            entry_ = builderForValue.build();
            onChanged();
          } else {
            entryBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public Builder mergeEntry(TransformMapProto.TransformMap.Transform value) {
          if (entryBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                entry_ != TransformMapProto.TransformMap.Transform.getDefaultInstance()) {
              entry_ =
                TransformMapProto.TransformMap.Transform.newBuilder(entry_).mergeFrom(value).buildPartial();
            } else {
              entry_ = value;
            }
            onChanged();
          } else {
            entryBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public Builder clearEntry() {
          if (entryBuilder_ == null) {
            entry_ = TransformMapProto.TransformMap.Transform.getDefaultInstance();
            onChanged();
          } else {
            entryBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public TransformMapProto.TransformMap.Transform.Builder getEntryBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getEntryFieldBuilder().getBuilder();
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        public TransformMapProto.TransformMap.TransformOrBuilder getEntryOrBuilder() {
          if (entryBuilder_ != null) {
            return entryBuilder_.getMessageOrBuilder();
          } else {
            return entry_;
          }
        }
        /**
         * <code>required .TransformMap.Transform entry = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            TransformMapProto.TransformMap.Transform, TransformMapProto.TransformMap.Transform.Builder, TransformMapProto.TransformMap.TransformOrBuilder> 
            getEntryFieldBuilder() {
          if (entryBuilder_ == null) {
            entryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                TransformMapProto.TransformMap.Transform, TransformMapProto.TransformMap.Transform.Builder, TransformMapProto.TransformMap.TransformOrBuilder>(
                    getEntry(),
                    getParentForChildren(),
                    isClean());
            entry_ = null;
          }
          return entryBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:TransformMap.TransformEntry)
      }

      static {
        defaultInstance = new TransformEntry(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:TransformMap.TransformEntry)
    }

    public static final int ENTRY_FIELD_NUMBER = 1;
    private java.util.List<TransformMapProto.TransformMap.TransformEntry> entry_;
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    public java.util.List<TransformMapProto.TransformMap.TransformEntry> getEntryList() {
      return entry_;
    }
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    public java.util.List<? extends TransformMapProto.TransformMap.TransformEntryOrBuilder> 
        getEntryOrBuilderList() {
      return entry_;
    }
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    public int getEntryCount() {
      return entry_.size();
    }
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    public TransformMapProto.TransformMap.TransformEntry getEntry(int index) {
      return entry_.get(index);
    }
    /**
     * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
     */
    public TransformMapProto.TransformMap.TransformEntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }

    private void initFields() {
      entry_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(1, entry_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entry_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TransformMapProto.TransformMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransformMapProto.TransformMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransformMapProto.TransformMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransformMapProto.TransformMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransformMapProto.TransformMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TransformMapProto.TransformMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TransformMapProto.TransformMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TransformMapProto.TransformMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TransformMapProto.TransformMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TransformMapProto.TransformMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TransformMapProto.TransformMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransformMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransformMap)
        TransformMapProto.TransformMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransformMapProto.internal_static_TransformMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransformMapProto.internal_static_TransformMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransformMapProto.TransformMap.class, TransformMapProto.TransformMap.Builder.class);
      }

      // Construct using TransformMapProto.TransformMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entryBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransformMapProto.internal_static_TransformMap_descriptor;
      }

      public TransformMapProto.TransformMap getDefaultInstanceForType() {
        return TransformMapProto.TransformMap.getDefaultInstance();
      }

      public TransformMapProto.TransformMap build() {
        TransformMapProto.TransformMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TransformMapProto.TransformMap buildPartial() {
        TransformMapProto.TransformMap result = new TransformMapProto.TransformMap(this);
        int from_bitField0_ = bitField0_;
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entry_ = java.util.Collections.unmodifiableList(entry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransformMapProto.TransformMap) {
          return mergeFrom((TransformMapProto.TransformMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransformMapProto.TransformMap other) {
        if (other == TransformMapProto.TransformMap.getDefaultInstance()) return this;
        if (entryBuilder_ == null) {
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
        } else {
          if (!other.entry_.isEmpty()) {
            if (entryBuilder_.isEmpty()) {
              entryBuilder_.dispose();
              entryBuilder_ = null;
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntryFieldBuilder() : null;
            } else {
              entryBuilder_.addAllMessages(other.entry_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TransformMapProto.TransformMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransformMapProto.TransformMap) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<TransformMapProto.TransformMap.TransformEntry> entry_ =
        java.util.Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = new java.util.ArrayList<TransformMapProto.TransformMap.TransformEntry>(entry_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          TransformMapProto.TransformMap.TransformEntry, TransformMapProto.TransformMap.TransformEntry.Builder, TransformMapProto.TransformMap.TransformEntryOrBuilder> entryBuilder_;

      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public java.util.List<TransformMapProto.TransformMap.TransformEntry> getEntryList() {
        if (entryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entry_);
        } else {
          return entryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public int getEntryCount() {
        if (entryBuilder_ == null) {
          return entry_.size();
        } else {
          return entryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public TransformMapProto.TransformMap.TransformEntry getEntry(int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);
        } else {
          return entryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, TransformMapProto.TransformMap.TransformEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
        } else {
          entryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, TransformMapProto.TransformMap.TransformEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.set(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder addEntry(TransformMapProto.TransformMap.TransformEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
        } else {
          entryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, TransformMapProto.TransformMap.TransformEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(index, value);
          onChanged();
        } else {
          entryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder addEntry(
          TransformMapProto.TransformMap.TransformEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, TransformMapProto.TransformMap.TransformEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder addAllEntry(
          java.lang.Iterable<? extends TransformMapProto.TransformMap.TransformEntry> values) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entry_);
          onChanged();
        } else {
          entryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public Builder removeEntry(int index) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.remove(index);
          onChanged();
        } else {
          entryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public TransformMapProto.TransformMap.TransformEntry.Builder getEntryBuilder(
          int index) {
        return getEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public TransformMapProto.TransformMap.TransformEntryOrBuilder getEntryOrBuilder(
          int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);  } else {
          return entryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public java.util.List<? extends TransformMapProto.TransformMap.TransformEntryOrBuilder> 
           getEntryOrBuilderList() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entry_);
        }
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public TransformMapProto.TransformMap.TransformEntry.Builder addEntryBuilder() {
        return getEntryFieldBuilder().addBuilder(
            TransformMapProto.TransformMap.TransformEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public TransformMapProto.TransformMap.TransformEntry.Builder addEntryBuilder(
          int index) {
        return getEntryFieldBuilder().addBuilder(
            index, TransformMapProto.TransformMap.TransformEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .TransformMap.TransformEntry entry = 1;</code>
       */
      public java.util.List<TransformMapProto.TransformMap.TransformEntry.Builder> 
           getEntryBuilderList() {
        return getEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          TransformMapProto.TransformMap.TransformEntry, TransformMapProto.TransformMap.TransformEntry.Builder, TransformMapProto.TransformMap.TransformEntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              TransformMapProto.TransformMap.TransformEntry, TransformMapProto.TransformMap.TransformEntry.Builder, TransformMapProto.TransformMap.TransformEntryOrBuilder>(
                  entry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:TransformMap)
    }

    static {
      defaultInstance = new TransformMap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TransformMap)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransformMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransformMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransformMap_Transform_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransformMap_Transform_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransformMap_TransformEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransformMap_TransformEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TransformMap.proto\"\264\003\n\014TransformMap\022+\n" +
      "\005entry\030\001 \003(\0132\034.TransformMap.TransformEnt" +
      "ry\032\356\001\n\tTransform\022\n\n\002id\030\001 \002(\t\022)\n\004type\030\002 \002" +
      "(\0162\033.TransformMap.TransformType\022\020\n\010logic" +
      "leT\030\003 \001(\001\022\020\n\010logicleW\030\004 \001(\001\022\020\n\010logicleM\030" +
      "\005 \001(\001\022\020\n\010logicleA\030\006 \001(\001\022\016\n\006logMin\030\007 \001(\001\022" +
      "\016\n\006logMax\030\010 \001(\001\022\016\n\006linMin\030\t \001(\001\022\016\n\006linMa" +
      "x\030\n \001(\001\022\020\n\010boundMin\030\013 \001(\001\022\020\n\010boundMax\030\014 " +
      "\001(\001\032E\n\016TransformEntry\022\013\n\003key\030\001 \002(\t\022&\n\005en" +
      "try\030\002 \002(\0132\027.TransformMap.Transform\"?\n\rTr",
      "ansformType\022\013\n\007LOGICLE\020\000\022\007\n\003LOG\020\001\022\n\n\006LIN" +
      "EAR\020\002\022\014\n\010BOUNDARY\020\003B\023B\021TransformMapProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TransformMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransformMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransformMap_descriptor,
        new java.lang.String[] { "Entry", });
    internal_static_TransformMap_Transform_descriptor =
      internal_static_TransformMap_descriptor.getNestedTypes().get(0);
    internal_static_TransformMap_Transform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransformMap_Transform_descriptor,
        new java.lang.String[] { "Id", "Type", "LogicleT", "LogicleW", "LogicleM", "LogicleA", "LogMin", "LogMax", "LinMin", "LinMax", "BoundMin", "BoundMax", });
    internal_static_TransformMap_TransformEntry_descriptor =
      internal_static_TransformMap_descriptor.getNestedTypes().get(1);
    internal_static_TransformMap_TransformEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransformMap_TransformEntry_descriptor,
        new java.lang.String[] { "Key", "Entry", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
